### ISSUE TITLE
Expose Subscription.mch for efficient subscribe

### ISSUE THREAD

**Issue by uwillis** [nats-io/nats#104]
Currently Subscribe() always spawns [a new routine](https://github.com/nats-io/nats/blob/master/nats.go#L1356). During fan-in with many subjects, this could easily blow up with many routines idling on <-s.mch (memory use: nsubs * 2 KB)

BindRecvChan unexpectedly does the same. SubscribeSync doesn't let me aggregate select in a single routine.

Exposing mch will let developers handle its own select and manage their own routine pools.

**Comment by derekcollison** [comment]
So you want to be able to run a select against multiple channels representing subscriptions without the extra goroutines, that correct?

**Comment by uwillis** [comment]
Correct.

I see that s.mch is too deep inside to be exposed though.
Just an idea for an API:
```
inbox := make(chan *nats.Msg, size) // user create his own inbox
nats.SubscribeChan("topic", inbox) 
```

Internally, you can do nonblocking send:
```
select {
  case inbox <- s.mch:
  default:
}
// do cleanup, mutex unlock, etc
```

User is responsible for predicting his own message rate (inbox size)

**Comment by derekcollison** [comment]
I think you raise a good point about being able to more closely control that aspect of the client. Let me give it some thought.

**Comment by schancel** [comment]
I'd like to second this issue.  I'm also running into a situation where I'd like to have direct access to the channel messages are sent on.  There's currently no way for a goroutine to easily process messages from nats, and messages from other goroutines.

e.g.

```go
select {
 case m <- subChan:
    ... dostuff
 case cm <- controlChannel:
    ... do other stuff
}
```

I'm not seeing any particular reason why `mch` couldn't be exposed with a little bit of refactoring.

**Comment by derekcollison** [comment]
I have been looking at this a bit. For your instance, I believe you can use this to achieve what you want: https://github.com/nats-io/nats#using-go-channels-netchan. In general I hide the internals because they are just that, internals, which I would like us to reserve the right to change and make better. I am working on that part.

**Comment by derekcollison** [comment]
Handled now by https://github.com/nats-io/nats/blob/master/nats.go#L1628
