### ISSUE TITLE
Multiple servers: subscribe then publish receives no message

### ISSUE THREAD

**Issue by uwillis** [nats-io/nats#108]
1. Start gnatsd at serverA and serverB
2. run client1 with `opts.Server = []string{serverA, serverB}`
3. subscribe client1 to a topic
4. run client2 with `opts.Server = []string{serverB, serverA}` . Note the sequence
5. client2 publish to topic continuously
6. client1 never receive messages

**Comment by derekcollison** [comment]
Send a simple test program that shows the issue, happy to take a look.

**Comment by uwillis** [comment]
Run two gnats at port 2222 and 3333, then run the following
https://gist.github.com/uwillis/2d56611284e43e84740d

**Comment by derekcollison** [comment]
Would need to see the configurations for the gnatsd that cluster them together.

**Comment by uwillis** [comment]
My bad, I was only using --routes flag. Using file config and it works.

Can I ask what's the cluster behavior during split brain (network partition) ?I tried to google but couldn't find any info.

**Comment by derekcollison** [comment]
NATS is a fire and forget substrate system, so under split brain, messages will be lost. Upon re-connectivity, the interest graph will heal, but messages that were sent during may be lost..
