### ISSUE TITLE
Any appetite for making subscription more like http.HandleFunc ?

### ISSUE THREAD

**Issue by byrnedo** [nats-io/nats#113]
Hi, 

Firstly Nats is great. :)

Secondly, I write http services that also communicate via nats internally. 
Since the http lib already has a standard way to register handlers it would, for my part, make life simpler if nats had the same convention. 

`nats.HandleFunc(<subject>, func(...){...})`

Is there any appetite for this? Is there a better forum in which to discuss this kind of thing?

For my own amusement I've an example here: https://github.com/byrnedo/apibase/blob/master/natsio/natsio_it_test.go#L112

**Comment by derekcollison** [comment]
Thanks for the feedback! Best place would be the google group, or possibly the Slack forum.

More information at http://nats.io/community/
