### ISSUE TITLE
Don't use channels for subscribers

### ISSUE THREAD

**Issue by derekcollison** [nats-io/nats#115]
This leads to bad behavior when lots of subscriptions exist.

**Comment by kozlovic** [comment]
What kind of bad behavior? Is it about memory or something else?

I see that a subscription is pretty expensive memory wise. The creation of the message channel for one is costly, especially when there is no pending messages. In C, the message has a pointer to a message, so I can have a linked list. The SubChanLen is replaced with a MaxPending count that is checked against a list's count value. So the subscription is smaller when there are no message pending, and as big as in Go when the list is "full".

**Comment by derekcollison** [comment]
Exactly, I will do a linked list impl as well. That is for tomorrow. ;)

**Comment by kozlovic** [comment]
And for the notification? Use channel too or regular condition variable?

PS: If you want, I can try to do that for you, unless you have something very specific in mind.

**Comment by derekcollison** [comment]
Regular condition variables. I have a plan, will be fun. Plan on coding it up tomorrow.
