### ISSUE TITLE
sendConnect() doesn't handle +OK when verbose is set

### ISSUE THREAD

**Issue by mcqueary** [nats-io/nats#118]
If the client's initial `CONNECT` message has `"verbose":true`, the server will reply with `+OK`. However, `sendConnect()` doesn't expect this, and will return an error.

**Comment by kozlovic** [comment]
Sounds like I introduced this when making the (re)connect process synchronous, right?

-- 
Ivan Kozlovic | Principal Engineer
http://github.com/kozlovic
Apcera Inc.

**Comment by derekcollison** [comment]
@kozlovic I think so..

**Comment by kozlovic** [comment]
Will send something soon...

**Comment by kozlovic** [comment]
Fixed by #120
