### ISSUE TITLE
Subscribe() accumulates callbacks

### ISSUE THREAD

**Issue by donileo** [nats-io/nats#122]
Is there a reason calling Subscribe on a topic should accumulate the callbacks?

For example:

Subscribe("a", callback)
Subscribe("a",callback)

will actually call the callback two times for every message received on topic "a". Seems different than what would I would expect which is that callback should only be called once per message sent on topic "a" no matter how many times the callback is subscribed.

**Comment by derekcollison** [comment]
Each subscribe creates a new subscription to the given topic with different and unique subscription IDs (sids).
