### ISSUE TITLE
Incorrect error from NextMsg(timeout) when max reached

### ISSUE THREAD

**Issue by mcqueary** [nats-io/nats#123]
The `NextMsg(timeout)` function interprets `s.mch == nil` as indicating that the connection is closed, and returns `ErrConnectionClosed`. This is an invalid assumption. `s.mch` having the value `nil` only means that the subscription has become invalid (removed via `removeSub(s)`), which will be true if the connection `close(...)` has been called, but it will also be true if the subscription's auto unsubscribe `max` has been reached. In this latter case, erroneously reporting that the connection is closed results in confusion.

Fortunately we have a reliable indicator of whether the subscription is invalid: the `closed` field. I propose that we remove the Conn checks from this method and simply check `closed` to see if the sub is still valid.

Therefore I propose replacing this:
```go
	if s.mch == nil {
		s.mu.Unlock()
		return nil, ErrConnectionClosed
	}
	if s.mcb != nil {
		s.mu.Unlock()
		return nil, errors.New("nats: Illegal call on an async Subscription")
	}
	if s.conn == nil {
		s.mu.Unlock()
		return nil, ErrBadSubscription
	}
	if s.sc {
		s.sc = false
		s.mu.Unlock()
		return nil, ErrSlowConsumer
	}
```
with this:
```go
	if s.closed {
		s.mu.Unlock()
		return nil, ErrBadSubscription
	}
	if s.mcb != nil {
		s.mu.Unlock()
		return nil, errors.New("nats: Illegal call on an async Subscription")
	}
	if s.sc {
		s.sc = false
		s.mu.Unlock()
		return nil, ErrSlowConsumer
	}
```

This results in two test changes. `TestClosedConnections` needs to test for `sub.NextMsg(10)` to return `nats.ErrBadSubscription` rather than `nats.ErrConnectionClosed`, and `TestClientSyncAutoUnsub` should test that the error returned from `sub.NextMsg(10 * time.Millisecond)` is `nats.ErrBadSubscription` (right now it only tests `err != nil`).

**Comment by kozlovic** [comment]
Larry, have a look at PR #107 for some background. I introduced s.closed in this PR, and at one point replaced the test of s.mch with s.closed, but we decided to keep using s.mch instead.

**Comment by mcqueary** [comment]
Ivan, I looked at them just now. The problem is that s.mch is always nil when s.closed is true, and vice versa. They are assigned in [close()](https://github.com/nats-io/nats/blob/master/nats.go#L1735-L1748) and in [removeSub()](https://github.com/nats-io/nats/blob/master/nats.go#L1458-L1471). We are using indirect indicators to figure out if the connection is closed, but none of them is distinct.

How about this:

```go
    if s.mch == nil {
        if s.delivered >= s.max {
            s.mu.Unlock()
            return nil, ErrBadSubscription
            // or 
            // return nil, ErrMaxMessages 
            // (a new error "nats: Max messages delivered", same as used later in this func)
        }
        s.mu.Unlock()
        return nil, ErrConnectionClosed
    }
    if s.mcb != nil {
        s.mu.Unlock()
        return nil, errors.New("nats: Illegal call on an async Subscription")
    }
    if s.conn == nil {
        s.mu.Unlock()
        return nil, ErrBadSubscription
    }
    if s.sc {
        s.sc = false
        s.mu.Unlock()
        return nil, ErrSlowConsumer
    }
```

**Comment by kozlovic** [comment]
I think that if we want to maintain `ErrConnectionClosed` at the top of this function, we would need to check `Conn.IsClosed()`. That would satisfy Derek comment in #106, which was: " So if the subscription is valid but connection was closed, return connection closed, otherwise return bad subscription.".

In other words, if connection is closed (explicitly or due to error? note that `close()` will set the status to what is given as an argument, so `IsClosed` maybe false although the connection is "closed"...), we will return `ErrConnectionClosed`, then, the next test can be `s.closed` or `s.mch == nil` to see if we return `ErrBadSubscription`. Finally, `if s.conn == nil` would then seem unnecessary.

Now, this would have an impact on performance, since we would have to grab the connection's lock, which we don't need as of now. So maybe we would need to pass some info to the subscription object when connection is closed, so that it can be accessed under the subscription lock.

**Comment by mcqueary** [comment]
Ivan, I don't believe we have any choice but to check for `conn == nil`, unless we change `Conn.removeSub()` to work differently.  If `removeSub()` has been called for this subscription, then `s.conn == nil`is guaranteed when entering this function, and calling s.conn.IsClosed() without a `nil` check would result in a nil pointer panic. In this case, how would we regain access to the parent connection to be able to call `Conn.IsClosed()`? I am still a Go neophyte, so perhaps I am missing some information regarding variable scope and visibility within compilation units.

**Comment by kozlovic** [comment]
True, and like I said, that would probably be costly. This is why I was saying that during the connection close, we go through the subscriptions to 'close' them. We could - under the subscription lock - set a new boolean (in the subscription object of course) indicating that the subscription is closed in result to the connection being closed. This boolean would be false when subscription is closed for any other reasons like in `removeSub()`. Then in `NextMsg()`, we would not need to look at `s.conn` anymore, and this new boolean would be checked to see if we return `ErrConnectionClosed` or the other error conditions. Let me know if that makes sense.

**Comment by mcqueary** [comment]
Sorry, I think I skipped the last sentence of your previous comment :) :+1: Yes, that's what I was thinking, too: a new boolean field set during `close()` that would definitively indicate what has happened. That makes the most sense to me... and you're right, checking `s.conn` would then be unnecessary.

**Comment by mcqueary** [comment]
#124 now incorporates what we talked about here. Please have a look.
