### ISSUE TITLE
doc: tls doesn't require DNS

### ISSUE THREAD

**Issue by glycerine** [nats-io/nats#148]
I mentioned this on Slack, but I thought it could be much better enunciated in the docs:

Gnatsd doesn't require a DNS entry for your server in order to utilize TLS certs. This actually makes TLS certs much, much more useful for backend systems stuff.  I'm concerned that people who don't take the time to experiment and discover this undocumented feature on their own may be put off by the concerns about needing to issue/handle true certs, when in reality a self-generated CA works just fine and provides production grade encryption.

**Comment by derekcollison** [comment]
Working with certs is a complicated issue for sure.

**Comment by glycerine** [comment]
opened https://github.com/nats-io/gnatsd/issues/181 as a proposal to simplify.

**Comment by mcqueary** [comment]
Jason, please feel free to submit a PR against the nats-io/gnatsd or nats-io/nats README, or the nats-io/nats-docs repo. Perhaps [the FAQ] (https://github.com/nats-io/nats-docs/blob/master/content/documentation/faq.md) would be a good spot?
