### ISSUE TITLE
how can subscriber know who is publisher

### ISSUE THREAD

**Issue by warmwine** [nats-io/nats#168]
as title

**Comment by warmwine** [comment]
if there is a lot publishers and one subscriber.
how can subscriber known which publisher is the one who send a certain message

**Comment by camros** [comment]
@warmwine there is now out of the box way to know who a given sender is. That is by design of nats. Servers and clients are decoupled. If you need to know who a given sender of a message is then your message producer (publisher) should include that information in your message.

**Comment by warmwine** [comment]
thanks a alot
