### ISSUE TITLE
go vet: assignment copies lock value to tlsCopy

### ISSUE THREAD

**Issue by magiconair** [nats-io/nats#175]
Not sure if this is an issue but you might want to have a look. I've stumbled over this while playing with the latest go tip build. It is not reported by go 1.6.

```
$ go version
go version devel +ac8d97b Sat Apr 2 12:38:00 2016 +0000 darwin/amd64

$ go vet github.com/nats-io/nats
github.com/nats-io/nats/nats.go:707: assignment copies lock value to tlsCopy: crypto/tls.Config contains sync.Once contains sync.Mutex
exit status 1
```

**Comment by derekcollison** [comment]
Thanks..

**Comment by derekcollison** [comment]
Currently there is no lock structure and as you point out it does not complain in 1.6. I would imagine they added a lock, so we will keep an eye out as new Go releases hit. Thanks again.
