### ISSUE TITLE
Possible to make `Request` return your own error?

### ISSUE THREAD

**Issue by jacktuck** [nats-io/nats#178]
Using req-rep could I return nil for _result_ and my own error for _err_?

```
result, err := nc.Request("user", props, 1000*time.Millisecond)

//So here I'm sending "foo" as the reply, is there any interface for sending an error along instead?
nc.Publish(msg.Reply, []byte("foo"))
```

**Comment by mcqueary** [comment]
Hi Jack (@jacktuck). What is it that you are trying to accomplish?

Request() is just a convenience API that does the following things:

- Creates and subscribes to a unique INBOX subject
- Publishes the provided message to the provided subject
- Waits for a response until the specified timeout expires
- Returns either the response, or an (NATS) error.

If the payload of the response that you send contains some application-specific error, you can parse that yourself and return the application-specific error.

Take a look at [how Request() is implemented](https://github.com/nats-io/nats/blob/master/nats.go#L1693-L1707) and you should get the idea.

If I were you, I'd wrap `Request()` in your own method that parses the (potential) error message from the payload and returns it as an Error.
