### ISSUE TITLE
What Error if MaxReconnects Reached?

### ISSUE THREAD

**Issue by JesusIslam** [nats-io/nats#181]
I need to reconnect when maximum re-connection attempt (possibly by creating a new connection) reached for my long running service. 

How do I know if Publish or Request got the error? 

What error type it returns (maybe nats.ErrConnectionClosed)? 

Or can I give the MaxReconnect a value of -1 for infinite reconnection attempt?

**Comment by derekcollison** [comment]
The Publish and Request will error correctly if the connection is closed, and yes -1 will make the reconnects try forever.

**Comment by JesusIslam** [comment]
@derekcollison Thank you for the confirmation.
