### ISSUE TITLE
SetPendingLimits() does not check for proper values

### ISSUE THREAD

**Issue by kozlovic** [nats-io/nats#183]
One could pass negative or even 0 for either limit and cause all messages to be dropped. Question is: do we want to allow `0` as a way to say "don't check for that", as in `SetPendingLimits(100000, 0)` if one would want to set a limit on the number, but not the size?

**Comment by derekcollison** [comment]
What should we be looking for? What are sane values?

Would we allow SetPendingLimits(1, 1)?

**Comment by kozlovic** [comment]
Not sure what we be a sane floor for both limits. Maybe we should just check that it is not `0` (does not make sense to have a subscription and prevent it from receiving anything) and maybe accept any negative value as a no-limit meaning? These could work independently, that is, `SetPendingLimits(xxx,-1)` means we don't care about the accumulated size and `SetPendingLimits(-1,xxx)` means we don't care about the count, but don't want more than that many bytes pending.

**Comment by derekcollison** [comment]
Seems reasonable. Want to do a PR?

**Comment by kozlovic** [comment]
Sure.
