### ISSUE TITLE
Should value returned by `Dropped()` be an int64?

### ISSUE THREAD

**Issue by kozlovic** [nats-io/nats#184]
Internally, `dropped` is defined as `int`. Since this is the total of dropped messages for the lifetime of the subscription, the number could potentially be high. Should we make this a `int64`?

**Comment by derekcollison** [comment]
If it is internal, we could change it. Do we surface as an int at any point in time? I think 2B should suffice but I understand what you are saying.

**Comment by kozlovic** [comment]
We have the exported api `Dropped()` that returns an `int`.

**Comment by kozlovic** [comment]
But I agree that if an application drops more than 2B messages, there are other problems than getting a negative value returned by `Dropped()`.

**Comment by derekcollison** [comment]
Since we have a public commitment to int, I say we leave as is.

**Comment by kozlovic** [comment]
As a remark, it seems that `int` is same size as `uint` and can be 32 or 64 bits. https://golang.org/ref/spec

```
There is also a set of predeclared numeric types with implementation-specific sizes:

uint     either 32 or 64 bits
int      same size as uint
uintptr  an unsigned integer large enough to store the uninterpreted bits of a pointer value
``` 
I think we should refrain from using `int` in the future for public APIs or when predictability of the range is required.

**Comment by derekcollison** [comment]
That is a true statement, and golang can be deployed on 32bit, but its quickly fading, almost always is 64bit.
