### ISSUE TITLE
Way to recover from panic with encoded conn

### ISSUE THREAD

**Issue by byrnedo** [nats-io/nats#191]
Is there any built in way to recover from panics occurring within a subscribed callback? Like when using the protobuf or json encoding?

**Comment by derekcollison** [comment]
Which panic are you seeing and does it happen in your callback or during decoding?

**Comment by byrnedo** [comment]
There's nothing wrong in nats decoding, just wondering in the case of my callback throwing a panic for whatever reason. I see that there's an `AsyncErrorCB` option for instance, but is there anything similar in the event of a callback panic?

**Comment by derekcollison** [comment]
If you are worried about your code, you can wrap or curry your actual subscription with one that catches any exceptions/panics.

**Comment by byrnedo** [comment]
Ok thanks.
