### ISSUE TITLE
Chan subscribers cannot receive more than 65536 messages (or 65536*1024 bytes).

### ISSUE THREAD

**Issue by kozlovic** [nats-io/nats#193]
Any Chan subscribers will stop receiving messages after any of the above limit is reached.

**Comment by pkieltyka** [comment]
is this a confirmed bug? sounds bad

**Comment by kozlovic** [comment]
I believe so (pending review), but it appeared around https://github.com/nats-io/nats/pull/132 (not specifically this commit maybe, but around this work). That is, this is specific to the new subscription type `ChanSubscription` that was introduced in `1.2.0`.

**Comment by rybit** [comment]
I confirmed this using a [tiny client](https://github.com/netlify/messaging/blob/master/nats-client/cmd/count_cmd.go) manually.
