### ISSUE TITLE
Published struct is never received by subscriber

### ISSUE THREAD

**Issue by perrohunter** [nats-io/nats#205]
I'm trying to publish a struct to NATS but in the following case the struct is never received by the subscriber, I have other encoded structs that are actually being received, this is a case that is not working for some reason, any idea what could be happening?

```
package main

import (
	"github.com/nats-io/nats"
	"fmt"
	"time"
)

type UserList struct {
	Users map[int]string `json:"users"`
}

func main() {
	xnc, _ := nats.Connect(nats.DefaultURL)
	nc, _ := nats.NewEncodedConn(xnc, nats.JSON_ENCODER)
	defer nc.Close()
	nc.Subscribe("usersChanged", func(m *UserList) {
		fmt.Printf("USERS CHANGED: %s\n", m)
	})
	for {
		users := make(map[int]string)

		users[1] = "perrohunter"
		users[2] = "charly"

		usrLst := &UserList{Users:users}
		nc.Publish("usersChanged", usrLst)
		time.Sleep(3800 * time.Millisecond)
	}
}

```

**Comment by derekcollison** [comment]
When I captured the error from nc.Publish() it returned the following.
```
json: unsupported type: map[int]string
```

Its good to capture errors ;)

The JSON marshaler only supports string key types for maps I believe.

https://groups.google.com/forum/#!topic/golang-nuts/xuFAnKfGMLE
