### ISSUE TITLE
How to pub and sub with ack

### ISSUE THREAD

**Issue by steventanwc** [nats-io/nats#208]
I have successfully run the Nats-Streaming Go clients to publish and subscribe and consume the message.

Would appreciate if someone can help me on how I pub and sub with ack and the ark results  can be called back in the client.

Another related question: If the message is delivered to subscriber successfully with an acr, will Nats Streaming Server automatically delete the message from the store? If no, how can we implement that? I know there is a max message in store for each channel, but the delivered messages will take up unnecessary storage.

Thank u in advance

Steven Tan

**Comment by kozlovic** [comment]
Closing this this was opened by mistake. Issue was opened in the go-nats-streaming repo: https://github.com/nats-io/go-nats-streaming/issues/101
