### ISSUE TITLE
Find out which subscriber is connected

### ISSUE THREAD

**Issue by steventanwc** [nats-io/nats#213]
Hi 

Is there a way to find out the id of the subscriber who is online or offline currently?

Regards

Steven

**Comment by kozlovic** [comment]
@steventanwc You have opened this issue against the client, so the answer would be no. In the server, you can query (with monitoring enabled and endpoint `connz?subs=1`) the list of subscriptions. However, the server does not keep the subscribers that are closed, so there is no way to get that list.
