### ISSUE TITLE
Can we please have documentation on the clustering protocol?

### ISSUE THREAD

**Issue by delfick** [nats-io/nats#215]
Hi,

We have a situation where we have gnats instances in a mesos setup, which means gnats instances can be killed and moved to somewhere else in the cluster at random times (i.e. a mesos slave going down).

We are currently running our gnats such that the --cluster is the same port as the -p option and the --routes points at the port our load balancer serves for the cluster of gnats.

This tends to work fine, however we’ve noticed that with enough traffic the clustering seems to fall apart and not recover.

To workaround this issue (for at least just the short term) we think some integration with mesos would be nice, where the --routes points at something that talks to mesos and gives back information about the active/dead gnats instances as they move around.

I tried making such a bridge today but I’m having a difficulty trying to work out a) if it’s even possible and b) what the protocol actually is.

So, long story short, if our idea is even feasible, can we get some documentation on what would be involved in implementing the clustering protocol?

Thanks!

**Comment by kozlovic** [comment]
Are you asking about the protocol between servers and clients, or between servers? If so, this issue should be opened against gnatsd repo. 

The first thing that comes to mind is that you should not be able to use the same port for `-cluster` and `p`, so I think you mean something different for port than just the port number.

What are the symptoms of the clustering falling apart? Which version of NATS Server are you using?

**Comment by ColinSullivan1** [comment]
@kozlovic - Thanks for jumping in.  I've started looking at documenting the protocol.

**Comment by delfick** [comment]
Ah yes, I did indeed mean to put this on the gnatsd repo, do you want me to recreate it there?

So what is meant to happen if --cluster -p have the same value?

The clustering appears to get into a split brain scenario. We're using 0.8.1.

We believe the problem has something to do with how we go to the load balancer to discover the other instances and can be sent back to the same server.

@ColinSullivan1 awesome, thanks :)

**Comment by kozlovic** [comment]
Yes, please create issue against gnatsd.
`-cluster` and `-p` can't have the same value, the server would fail to start. Will try to 0.8.1, but tested with latest and definitively not possible. I would recommend using 0.9.4. There has been cluster issues fixed in the most recent releases.

**Comment by delfick** [comment]
ok, fair enough, we will certainly look at that upgrade.
