### ISSUE TITLE
Pending messages cleanup

### ISSUE THREAD

**Issue by lukaf** [nats-io/nats#217]
Hi,

Is it possible to have an async subscriber stop receiving new messages and clean the existing ones present in the queue (inspected by subscription.Pending)?

Thank you!

**Comment by ColinSullivan1** [comment]
@lukaf Not really - a subscriber will continue to receive messages until it is closed, and at that point it will internally clean up any pending messages.  Could you describe your use case?

**Comment by lukaf** [comment]
Hi @ColinSullivan1,

Thanks for the answer. Could you explain a bit what do you mean with 'until it is closed'? Does this refer to connection or subscription? And does cleaning up pending messages mean discarding them?

Basic use case would be gracefully stopping consumers, so that they stop receiving old messages but process current ones and the ones in the queue (pending).

Thank you!

**Comment by ColinSullivan1** [comment]
@lukaf No problem!  Sorry for the confusion - I was referring to the subscription being unsubscribed, but the connection close will do the same.  NATS is at most once delivery; when there is no longer interest so the messages will be discarded.

To avoid lost messages, I suggest you look into [NATS Streaming](http://nats.io/documentation/streaming/nats-streaming-intro)?  It will solve this problem for you.

In both NATS and NATS streaming, we have queue subscribers to distribute work.  You can find information about that [here] (http://nats.io/documentation/concepts/nats-queueing).

The **NATS streaming server** will send messages to the queue subscriber that has the least number of outstanding acknowledgements (the most efficient subscriber), distributing work more fairly, which looks to be in line with your goals.  When you unsubscribe, messages that have been sent to that queue subscriber have not been acknowledged (processed) will automatically be resent to other queue subscribers in the queue group.  _Note, the NATS server will distribute messages to a queue subscriber randomly._  

If you prefer not to use NATS streaming, we can discuss other alternatives, such as a control plane to allow subscribers to gracefully shut down...

Lowering the `max_pending_size` at the server will work, but is the brute force approach - a subscriber too far behind will be automatically disconnected and you will still lose messages.

Does NATS streaming sound like it will work for you?

**Comment by lukaf** [comment]
Wow, wasn't even aware NATS streaming exists. It looks like exactly what I'm looking for.
Thank you very much!

**Comment by mcqueary** [comment]
@lukaf That's what we like to hear 👍

**Comment by ColinSullivan1** [comment]
Absolutely, happy to help!
