### ISSUE TITLE
Subscribe("foo", nil) inconsistency between Conn and EncodedConn

### ISSUE THREAD

**Issue by rbucker** [nats-io/nats#48]
EncodedConn.Subscribe("foo", nil) throws a nil pointer exception instead of deleting the subscription as documented in the README.

Conn.Subscribe("foo", nil) returns normally but does not delete the subscription.

Since there is a Subscription.Unsubscribe() then this 'nil' behavior should be avoided and either return an error in the error field or throw an exception. Looking into the Subscribe code there is some code that looks for a nil callback and some that throws an exception when reflecting.

**Comment by derekcollison** [comment]
This in the README correct?

**Comment by rbucker** [comment]
Yep. I was tinkering with the code before I went to the examples.

**Comment by derekcollison** [comment]
Send a PR.. ;)

**Comment by rbucker** [comment]
The readme file indicates that c.Subscribe("foo", nil) will unsubscribe and while this method does not throw a nil exception the nc.Subscribe("foo", nil) does. Since (a) the client can register more than on subscription the nil param would seem to be bogus. So If I were to generate a PR for this I'm going to add a check for nil in both subscribe(s) and throw an exception if the handler is nil. (If you had intentionally subscribed more than once then the nil option would not know which one to disable.)

If you agree then I'll implement the Fatal() of the handler is nil. Otherwise the doc should be updated. (just depends on the intent)

PS: looking at the Ruby version of the client code it appears that there is no analog for the subscribe("foo", nil).

**Comment by rbucker** [comment]
There are two possible solutions. I documented them in the tkt. I do not have the historical perspective to have a strong position other than the aesthetic of using a Subscribe() function to Unsubscribe() when there is already an Unsub function().

Richard Bucker
http://about.me/richard.bucker

**Comment by rbucker** [comment]
One more thing. There is a testcase in conn_test.go that tests Subscribe("foo", nil). As I indicated Conn.Subscribe() does not throw an exception but it also does not operate properly. The test cases would also need to be evaluated.

**Comment by derekcollison** [comment]
Will take a look when I have some time.. Thanks..

**Comment by rbucker** [comment]
I found this comment in the code:
If no MsgHandler is given, the subscription is a synchronous subscription and can be polled via Subscription.NextMsg().

**Comment by derekcollison** [comment]
A normal connection with no handler creates a synchronous subscriber, however will look at the EncodedConn version more closely..

**Comment by derekcollison** [comment]
EncodedConn is not built currently for NextMsg, I will add an err return though.
