### ISSUE TITLE
Will not reconnect on "connection reset by peer" errors

### ISSUE THREAD

**Issue by clsung** [nats-io/nats#51]
We've got a error msg like
> write tcp x.y.z.w:4222: connection reset by peer
> nats: Connection Closed

and never get reconnectCallBack called.

The related traceback is:
> github.com/apcera/nats.(*Conn).close(0xc208084000, 0x2, 0xc20802b001)
    /gopath/src/github.com/apcera/nats/nats.go:1620 +0x34e
> github.com/apcera/nats.(*Conn).Close(0xc208084000)
    /gopath/src/github.com/apcera/nats/nats.go:1630 +0x36
> github.com/apcera/nats.(*Conn).processErr(0xc208084000, 0xc208087d20, 0x12)
    /gopath/src/github.com/apcera/nats/nats.go:1129 +0x1dd
> github.com/apcera/nats.(*Conn).parse(0xc208084000, 0xc2080ca000, 0x19, 0x8000, 0x0, 0x0)
    /gopath/src/github.com/apcera/nats/parser.go:222 +0xb9a
> github.com/apcera/nats.(*Conn).readLoop(0xc208084000)
    /gopath/src/github.com/apcera/nats/nats.go:942 +0x371
> created by github.com/apcera/nats.(*Conn).spinUpSocketWatchers
    /gopath/src/github.com/apcera/nats/nats.go:461 +0x6a

It would be good if processErr() also checks if there's any "connection reset by peer" msg?

**Comment by derekcollison** [comment]
Did the client truly reconnect?

**Comment by derekcollison** [comment]
Did the server ever come back up before the client timed out retries?
