### ISSUE TITLE
check if key exists

### ISSUE THREAD

**Issue by ClanStyles** [nats-io/nats#66]
Can I check if a data exists in the system?

example: "func (nc *Conn) Request(subj string, data []byte, timeout time.Duration) (m *Msg, err error)"
Request("subject", string("data"),...) check if "data" exists.

**Comment by derekcollison** [comment]
Apologize not following. What do you want to check? if you are using an encoded Connection that expects a string then I believe if there was not payload you will get an empty string ("").
