### ISSUE TITLE
Possible problem with flusher() not exiting

### ISSUE THREAD

**Issue by kozlovic** [nats-io/nats#67]
I saw an issue where the flusher() seem not to exit. A test case running with "-race" also often shows this:

Ivans-MacBook-Pro:nats ivan$ go test -race -v -run AuthServers
=== RUN   TestAuthServers
==================
WARNING: DATA RACE
Write by goroutine 6:
  github.com/nats-io/nats.(*Conn).processConnectInit()
      /Users/ivan/dev/go/src/github.com/nats-io/nats/nats.go:517 +0x1ad
  github.com/nats-io/nats.(*Conn).connect()
      /Users/ivan/dev/go/src/github.com/nats-io/nats/nats.go:546 +0x23e
  github.com/nats-io/nats.Options.Connect()
      /Users/ivan/dev/go/src/github.com/nats-io/nats/nats.go:263 +0x1e5
  github.com/nats-io/nats.TestAuthServers()
      /Users/ivan/dev/go/src/github.com/nats-io/nats/cluster_test.go:113 +0x265
  testing.tRunner()
      /usr/local/Cellar/go/1.5/libexec/src/testing/testing.go:456 +0xdc

Previous read by goroutine 11:
  github.com/nats-io/nats.(*Conn).flusher()
      /Users/ivan/dev/go/src/github.com/nats-io/nats/nats.go:1066 +0x7a

Goroutine 6 (running) created at:
  testing.RunTests()
      /usr/local/Cellar/go/1.5/libexec/src/testing/testing.go:561 +0xaa3
  testing.(*M).Run()
      /usr/local/Cellar/go/1.5/libexec/src/testing/testing.go:494 +0xe4
  main.main()
      github.com/nats-io/nats/_test/_testmain.go:268 +0x20f

Goroutine 11 (running) created at:
  github.com/nats-io/nats.(*Conn).spinUpSocketWatchers()
      /Users/ivan/dev/go/src/github.com/nats-io/nats/nats.go:466 +0xa0
==================
--- FAIL: TestAuthServers (2.02s)
	cluster_test.go:120: Wrong error, wanted Auth failure, got 'nats: Timeout'
FAIL
exit status 1
FAIL	github.com/nats-io/nats	2.030s

**Comment by derekcollison** [comment]
Fixed with last PR merge..  https://github.com/nats-io/nats/pull/75
