### ISSUE TITLE
ReadLine() does not guarantee that the full line is read, which may cause parser to error out

### ISSUE THREAD

**Issue by kozlovic** [nats-io/nats#68]
When receiving the INFO protocol message, the call to ReadLine() assumes that the line will be received entirely, or the "pre" boolean will be true should the buffer be not big enough.
Actually, ReadLine() may return with a partial read, which if it contains at least "INFO" would make processExpectedInfo() to return ok, but then would make the readLoop fail on processing the remaining of the protocol. 
This can be demonstrated by having gnatsd's sendInfo() send part of the buffer, pause for a second and then send the rest of the buffer.

**Comment by derekcollison** [comment]
Want to submit a PR?

**Comment by kozlovic** [comment]
Not sure what the fix is going to be yet. But I question the usefulness of ReadLine since this function returns a line without the CRLF but yet does not return an error if not getting the full line... in other words there is no way to check that we have the line or not.
I guess we would need to read until the deadline and then check for CRLF and strip it if present. Will give it more thought.

**Comment by derekcollison** [comment]
I will fix this, but in next release most likely..

**Comment by kozlovic** [comment]
Closing this since this was resolved with #95
