### ISSUE TITLE
Panic on 386 systems

### ISSUE THREAD

**Issue by phifty** [nats-io/nats#72]
2015/09/14 15:19:26 http: panic serving 127.0.0.1:34640: runtime error: invalid memory address or nil pointer dereference
goroutine 19 [running]:
net/http.(*conn).serve.func1(0x18902060, 0xf76aa860, 0x188fc040)
	/opt/go/src/net/http/server.go:1287 +0xa2
sync/atomic.AddUint64(0x1887b964, 0x1, 0x0, 0x188fe240, 0x4)
	/opt/go/src/sync/atomic/asm_386.s:112 +0xc
github.com/nats-io/nats.(*Conn).subscribe(0x1887b880, 0x1892c0f0, 0x21, 0x0, 0x0, 0x0, 0x4, 0x0, 0x0, 0x0)
	/home/philipp/projects/go/src/github.com/nats-io/nats/nats.go:1298 +0x23d
github.com/nats-io/nats.(*Conn).Request(0x1887b880, 0x188ce620, 0x19, 0x188f6320, 0x12, 0x20, 0x540be400, 0x2, 0x0, 0x0, ...)
	/home/philipp/projects/go/src/github.com/nats-io/nats/nats.go:1254 +0x6f

It's a known issue on 386 system that handle 64bit numbers: https://github.com/golang/go/issues/6404

**Comment by derekcollison** [comment]
Thanks..
