### ISSUE TITLE
make sendPing exported

### ISSUE THREAD

**Issue by yehezkielbs** [nats-io/nats#81]
So application can send Ping to server when it wants to.

**Comment by kozlovic** [comment]
As you may know, you can already configured the ping interval Options.PingInterval, and the connection has two exported methods sending a PING and getting a PONG back: Conn.Flush() and Conn.FlushTimeout().

Would you mind letting us know why being able to call sendPing() at the application level would be useful?

**Comment by yehezkielbs** [comment]
OK, nevermind. I can just use Flush() & FlushTimeout()
