### ISSUE TITLE
Reconnect logic flawed when servers in the list require authentication

### ISSUE THREAD

**Issue by kozlovic** [nats-io/nats#87]
As I was trying to change the C client to do connect asynchronously, it occurred to me that there is a problem due to the asynchronous nature during the reconnect process in the GO client.
If the client is connected to a server, and one in the list requires authentication while the client does not have it (or does not match), then when the client is disconnected and try to connect to that server, as long as the TCP connection succeeds and the expected INFO is ok, it will assume that it is connected. In reality, when the readLoop is started, it will get a -ERR with Authorization Violation, which will cause the connection to be closed. If we were doing the (re)connect process "synchronous", then we would better handle this situation.

[TestAuthFailToReconnect.txt](https://github.com/nats-io/nats/files/14635/TestAuthFailToReconnect.txt)

**Comment by derekcollison** [comment]
Synch reconnect may make more sense after the async condition is detected.

**Comment by kozlovic** [comment]
Closing this since solved with #95.

**Comment by camros** [comment]
I am trying to understand the PING being sent after CONNECT with reference to the protocol docs. It's not necessary to send a ping after the connect. I do not understand by this was applied to the go client.

Am I wrong in assuming that for now this is hack to get around a sync/sync cleanliness of starting a new connection? This comment applies only to sending ping after connect and waiting for pong.

**Comment by kozlovic** [comment]
Jeff, the connect process is using non-blocking sockets, so that we can timeout the process. Doing a PING/PONG ensures that the client knows that the server has properly processed the connection init request, otherwise it would not know for sure. Does that make sense?

**Comment by camros** [comment]
Understood/confirmed. Thanks!

**Comment by mcqueary** [comment]
I have implemented the same logic in the Java client.

On Sun, Nov 8, 2015 at 8:57 PM, Jeff Marshall <notifications@github.com>
wrote:

> Understood/confirmed. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nats-io/nats/issues/87#issuecomment-154912063>.
>



-- 
*Larry McQueary* | Director, Messaging Technology
larry@apcera.com | @mcqueary | github.com/mcqueary
