### ISSUE TITLE
Can't customize TLS connection configuration

### ISSUE THREAD

**Issue by smithwinston** [nats-io/nats#93]
In `makeTLSConn()` it hard codes the following for the TLS Client configuration:

```
&tls.Config{InsecureSkipVerify: true}
```

If there was an instance of `tls.Config` in the `Opts` structure, the `makeTLSConn()` could use it (with the default as above).  The user could then override the TLS configuration to allow for custom certificates, specifying TLS versions, Cipher suites etc).

**Comment by derekcollison** [comment]
Once work on formal TLS is finishing up will relook at the clients who supported it with the old ruby based server.

**Comment by derekcollison** [comment]
This is handled now via https://github.com/nats-io/nats/commit/355b5b97e0842dc94f1106729aa88e33e06317ca
