### ISSUE TITLE
Readme.md code has a bug. 

### ISSUE THREAD

**Issue by jduhamel** [nats-io/nats#94]
While I know the Readme sample code is just sample. It is incorrect. The line that reads
```err := nc.Request("help", "help me", &response, 10*time.Millisecond)```

should be 
``` err := c.Request("help", "help me", &response, 10*time.Millisecond)```

also (very minor nit.) err is defined but not used. ;)

**Comment by mcqueary** [comment]
Thanks Joe, we'll fix it ;)

**Comment by mcqueary** [comment]
Fixed with `675093b`
