### ISSUE TITLE
Remove unused func serversAvailable()?

### ISSUE THREAD

**Issue by mcqueary** [nats-io/nats#99]
This is just housekeeping, but [`func (nc *Conn) serversAvailable() bool`](https://github.com/nats-io/nats/blob/master/nats.go#L300-307) doesn't appear to be referenced anywhere.

/cc @derekcollison

**Comment by derekcollison** [comment]
I think it may have been removed with @kozlovic latest changes.

**Comment by kozlovic** [comment]
I did not remove it, but looking at the history (went back to 2013), it was there but it look like it was never used.

**Comment by derekcollison** [comment]
Good catch then Larry! Apologies..
